version: '3.8'

services:
  marketbridge:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8080:8080"  # Web interface
      - "8765:8765"  # WebSocket API
    volumes:
      - ../logs:/app/logs  # Persist logs
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8080/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Add nginx reverse proxy for production
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro  # SSL certificates (if using HTTPS)
    depends_on:
      - marketbridge
    restart: unless-stopped
    profiles:
      - production
